# Generated by Django 5.1 on 2024-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
